---
title: "M7 Data Analysis: Nonparametrics"
author: "Matthew Ragoza"
date: "11/10/2021"
always_allow_html: true
output:
  github_document:
    toc: true
  html_document:
    df_print: paged
    toc: true
    number_sections: true
    toc_depth: '3'
    code_folding: hide
---

```{R, echo=FALSE, message=FALSE, warning=FALSE}
require(knitr)
# Set so that long lines in R will be wrapped:
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE)
library('ggplot2')
library('dplyr')
library('tidyverse')
library('kableExtra')
library('DescTools')
library('janitor')

load('RA_treatment.RData')
ra$Biologics <- factor(ra$Biologics, 0:1, c('Not treated w/ biologics', 'Treated w/ biologics'))
ra$CDAI_YN <- factor(ra$CDAI_YN, 1:2, c('CDAI not measured', 'CDAI measured'))
ra$Age <- factor(ra$AgeGp, 1:2, c('40-70', '75+'))
```

# Treatment of rheumatoid arthritis with biologics

This study involved a sample of patients in two different age groups with rheumatoid arthritis (RA) at a clinic in Philadelphia. One aspect of the study was to understand the relationships between the age group, a measure of disease activity called the Clinical Disease Activity Indicator (CDAI), and treatment of the disease with biologic medication.

The first research question we will investigate is whether treatment of arthritis with biologics was associated with disease activity, measured by CDAI. We can numerically compare measures of center and spread of the CDAI measurement grouped by treatment with biologics, as seen in Table 1. For those not treated with biologics, the mean of CDAI (12.2) was higher than the median (10). For those treated with biologics, the mean (14.0) was also higher than the median (10). This indicates that the distributions of CDAI were right-skewed. The median and IQR of CDAI were the same regardless of receiving biologics treatment, but the differences in the 1st and 3rd quartile imply that the distributions might be shifted. Upon examining the side-by-side box plots of CDAI seen in the Figure 1, it appears that CDAI may be shifted slightly higher for those treated with biologics.

```{R}
ra %>%
    drop_na(cdai) %>%
    group_by(Biologics) %>%
    summarise(
        n=n(),
        mean=mean(cdai),
        SD=sd(cdai),
        Q1=quantile(cdai, 0.25),
        Q2=quantile(cdai, 0.50),
        Q3=quantile(cdai, 0.75),
        IQR=quantile(cdai, 0.75)-quantile(cdai, 0.25),
        min=min(cdai),
        max=max(cdai),
        range=max(cdai)-min(cdai)
    ) %>%
    mutate_if(is.numeric, round, digits=1) %>%
    kable() %>%
    kable_styling()
```
**Table 1.** Measures of center and spread for CDAI by treatment with biologics.

```{R fig.height=4, fig.width=4}
ra %>%
    drop_na(Biologics) %>%
    ggplot(aes(
        x=Biologics,
        y=cdai,
    )) +
    geom_boxplot(na.rm=TRUE, width=0.5) +
    xlab('Treatment with biologics') +
    ylab('CDAI') +
    theme_classic() +
    theme(
        panel.grid.major.y=element_line(color='grey80'),
    )
```

**Figure 1.** Side-by-side box plots of CDAI by treatment with biologics.

We will use a nonparametric statistical test to answer the research question. The parameter(s) of interest are the population medians of CDAI for the treatment groups. The null hypothesis is that there is no difference between the median CDAI for the treatment groups. The alternative hypothesis is that the median CDAI is greater for those treated with biologics than those who were not. It seems from the similar skewness and IQR of the two CDAI distributions that the have they same shape. In addition, we can assume based on the study design that we have two independent random samples. Therefore, the conditions are met to apply a Wilcoxon rank sum test. We will now perform the test at a significance level of 0.05.

```{R}
alpha = 0.05
ra$Biologics2 <- -as.numeric(ra$Biologics) # change level order
wilcox.test(cdai ~ Biologics2, data=ra, alternative='greater')
```
The p-value of 0.134 indicates that we would have a 13.4% chance of getting a test statistic this high if the null hypothesis were true. Since we chose a significance level of 5%, the test statistic is not in the rejection region, so we fail to reject the null hypothesis. We do not have sufficient evidence to conclude that the population median CDAI is greater for the group that was treated with biologics than the group that was not. If we wanted to use a more efficiency statistical test, we could have used a two sample t test with unequal variance. The only additional condition for this test is that we have at least 30 individuals in each sample, or that they be normally distributed. The skewness of the distributions would make it unlikely that they are normal, but the sample sizes of 102 and 104 are both greater than 30, so the conditions for the parametric test are satisfied.

# CDAI measurement and age group

The next question we will address is whether there is a difference between the age groups in the likelihood that CDAI was measured at all. We can summarize this numerically as a table of the counts and relative frequencies of CDAI measurement for each age group, seen in Table 2. Out of the 459 individuals in the 40-70 age range, 193 had CDAI measured (42.0%). In contrast, only 13 of the 71 individuals in 75+ age group (18.3%) had CDAI measured. This difference is visually apparent in the relative frequency bar plot depicted in Figure 2.

```{R}
ra %>%
    group_by(Age, CDAI_YN) %>%
    count() %>%
    spread(key=CDAI_YN, value=n) %>%
    adorn_totals(where=c('row', 'col')) %>%
    mutate(
        `% CDAI not measured`=`CDAI not measured`/Total*100,
        `% CDAI measured`=`CDAI measured`/Total*100,
        `% Total`=(`CDAI not measured`+`CDAI measured`)/Total*100
    ) %>%
    mutate_if(is.numeric, round, digits=1) %>%
    kable() %>%
    kable_styling()
```
**Table 2.** Two-way table of whether CDAI was measured by age group. The table has been extended with relative frequencies for each age group.

```{R fig.height=4, fig.width=6, message=FALSE}
ra %>%
    group_by(Age, CDAI_YN) %>%
    summarise(count=n()) %>%
    mutate(freq=100*count/sum(count)) %>%
    ggplot(aes(
        x=Age, 
        y=freq,
        fill=CDAI_YN
    )) +
    geom_bar(position='stack', stat='identity', width=0.5) +
    scale_y_continuous(expand=c(0,0)) +
    xlab('Age') +
    ylab('Relative frequency (%)') +
    labs(fill=NULL) +
    theme_classic() +
    scale_fill_grey() +
    theme(
        panel.grid.major.y=element_line(color='grey80'),
    )
```

**Figure 2.** Bar plot of relative frequency of CDAI measurement by age group.

We want to use a nonparametric test to evaluate whether there is an association between the patients' age range and whether CDAI was measured. The null hypothesis is that the frequency of CDAI measurement is independent of the age range of the patients. The alternative hypothesis is that the frequency of CDAI measurement is dependent on the age range of the patients. We can assume that the study used a simple random sample of patients, so the criteria are satisfied to use Fisher's exact test. We will now run the test at a significance level of 0.05.

```{R}
alpha = 0.05
m <- matrix(c(266, 58, 193, 13), nrow=2)
fisher.test(m)
```
The p-value of 0.00012 indicates that we would have a 0.012% chance of obtaining a table of counts this extreme if the null hypothesis were true. Since we set the significance level at 5%, we can safely reject the null hypothesis. We have very strong evidence that the likelihood of having CDAI measured is dependent on the age range of the patient. The odds ratio of 0.31 indicates that patients in the 75+ age range had about 3 times lower odds of having their CDAI measured than patients in the 40-70 age range. If we wanted to use a parametric hypothesis test instead, the most appropriate test would be a chi-squared test of independence. This would necessitate that each cell in the two-way table have at least 5 expected counts assuming that the variables are independent. We can quickly test if this is the case by the fact that the cell with the fewest expected counts would have 206*71/530 = 27.6 counts, which is greater than 5. Therefore, we could have used the chi-squared test if we wanted to.

# Treatment with biologics and age group

The final question we will investigate is whether there is a difference between the age groups in the likelihood of receiving treatment with biologics. Table 3 shows a numerical summary of the counts and relative frequency of receiving biologics treatment for each age group. Out of the 459 patients in the 40-70 age group, 187 were treated with biologics (40.7%). On the other hand, only 10 out of the 70 patients in the 75+ age group (14.3%) received treatment with biologics. The relative frequency bar plot in Figure 3 highlights this disparity in biologics treatment by age group.
```{R}
ra %>%
    drop_na(Biologics) %>%
    group_by(Age, Biologics) %>%
    count() %>%
    spread(key=Biologics, value=n) %>%
    adorn_totals(where=c('row', 'col')) %>%
    mutate(
        `% Not treated w/ biologics`=`Not treated w/ biologics`/Total*100,
        `% Treated w/ biologics`=`Treated w/ biologics`/Total*100,
        `% Total`=(`Treated w/ biologics`+`Not treated w/ biologics`)/Total*100
    ) %>%
    mutate_if(is.numeric, round, digits=1) %>%
    kable() %>%
    kable_styling()
```
**Table 3.** Two-way table of treatment with biologics by age group. The table has been extended with relative frequencies for each age group.

```{R fig.height=4, fig.width=6, message=FALSE}
ra %>%
    drop_na(Biologics) %>%
    group_by(Age, Biologics) %>%
    summarise(count=n()) %>%
    mutate(freq=100*count/sum(count)) %>%
    ggplot(aes(
        x=Age, 
        y=freq,
        fill=Biologics
    )) +
    geom_bar(position='stack', stat='identity', width=0.5) +
    scale_y_continuous(expand=c(0,0)) +
    xlab('Age') +
    ylab('Relative frequency (%)') +
    labs(fill=NULL) +
    theme_classic() +
    scale_fill_grey() +
    theme(
        panel.grid.major.y=element_line(color='grey80'),
    )
```

**Figure 3.** Bar plot of relative frequency of treatment with biologics by age group.

Again, we would like to use a nonparametric test to determine whether there is an association between the patient's age range and whether they received treatment with biologics. The null hypothesis is that the frequency of treatment with biologics is independent of the age range of the patients. The alternative hypothesis is that the frequency of treatment with biologics is dependent on the age range of the patients. We have already assumed that the patients in the study were a simple random sample, so the requirements to apply Fisher's exact test are met. We will now run the test using a significance level of 0.05.

```{R}
alpha = 0.05
m <- matrix(c(272, 60, 187, 10), nrow=2)
fisher.test(m)
```
The p-value of 8.9e-06 indicates that we would have almost zero chance of observing a table of counts this drastic if the null hypothesis were true. We are using a significance level of 5%, so we can confidently reject the null hypothesis. We have very strong evidence that the likelihood of receiving treatment with biologics is dependent on the age range of the patient. The odds ratio of 0.24 implies that patients in the 75+ age group had about 4 times lower odds of receiving biologics treatment than those in the 40-70 age range. To check whether a chi-squared test of independence could have been used, we can check that there would be at least 5 expected counts in each cell if the variables were independent. We only have to check this in the cell with the fewest expected counts, which would have 197*70/529 = 26.1 counts. This is greater than 5, so the conditions would have been satisfied for the chi-squared test.

From the previous two analyses, we now know that patients in the 75+ age group were less likely to have their CDAI measured and less likely to receive treatment with biologics. In the first analysis we looked at the relationship between biologics treatment and CDAI. In that section, we dropped the missing values of CDAI from the data frame before conducting the analysis. However, if there were fewer CDAI measurements in the patients that did not receive biologics treatment, the missing data could have biased the result. Older patients would probably tend to have more severe CDAI scores, and they were less likely to be treated with biologics. Therefore, the missing data would probably shift the distribution of CDAI upwards for the group that did not receive biologics, which could potentially reverse the result of the statistical test if the shift were drastic enough.
