---
title: "M9 Data Analysis: Linear Regression"
author: "Matthew Ragoza"
date: "12/9/2021"
always_allow_html: true
output:
  github_document:
    toc: true
  html_document:
    df_print: paged
    toc: true
    number_sections: true
    toc_depth: '3'
    code_folding: hide
---

```{R, echo=FALSE, message=FALSE, warning=FALSE}
require(knitr)
# Set so that long lines in R will be wrapped:
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE)
library('ggplot2')
library('dplyr')
library('tidyverse')
library('kableExtra')
library('DescTools')
library('janitor')
library('reshape2')

load('laryngoscope.RData')
lar <- laryngoscope
remove(laryngoscope)
#hsb2$SES <- factor(hsb2$ses, levels=c('low', 'middle', 'high'))
#hsb2$program <- factor(hsb2$prog, levels=c('academic', 'general', 'vocation'))
```

# Tracheal Intubation and Age

The research question we would like to answer is whether there is a linear relationship between the age of the patient and the ease of intubation, where a higher score indicates a more difficult intubation procedure. Numerical summaries of each variable using measures of center and spread can be seen in Table 1. The age range of the sample is 20 to 77, with a mean of 49.4 and standard deviation of 13.1 Since the median of 51 is slightly higher than the mean, the age distribution is slightly left-skewed. The ease of intubation for this sample ranged from 0 to 100 with a mean of 40.8 and standard deviation of 28.5. The intubation score distribution was more right-skewed, since the median of 37.5 was less than the mean. We can jointly compare the distributions of age and ease of intubation using the scatter plot shown in Figure 1. There appears to be a slight positive correlation between the ease of intubation and the age of the patient based on the joint distribution of the points in the scatter plot.

```{R message=FALSE}
lar %>%
    select(c('age', 'ease')) %>%
    melt(value.name='value') %>%
    drop_na(value) %>%
    group_by(variable) %>%
    summarise(
        n=n(),
        mean=mean(value),
        SD=sd(value),
        Q1=quantile(value, 0.25),
        Q2=quantile(value, 0.50),
        Q3=quantile(value, 0.75),
        IQR=quantile(value, 0.75)-quantile(value, 0.25),
        min=min(value),
        max=max(value),
        range=max(value)-min(value)
    ) %>%
    mutate_if(is.numeric, round, digits=1) %>%
    kable() %>%
    kable_styling()
```
**Table 1.** Measures of center and spread for age and ease of tracheal intubation.

```{R fig.height=4, fig.width=4, message=FALSE}
lar %>%
    drop_na(ease) %>%
    ggplot(aes(
        x=age,
        y=ease,
    )) +
    geom_point() +
    geom_smooth(method='lm') +
    xlab('Age of patient') +
    ylab('Ease of tracheal intubation') +
    theme_classic()

```

**Figure 1.** Scatter plot of ease of tracheal intubation and age along with linear regression model and confidence interval.

We can statistically test the relationship between the variables using linear regression. We must first check whether the assumptions of linear regression are satisified. We can assume based on the study design that the values of the outcome variable, the ease of tracheal intubation, are independent. We will also surmise based on visual assessment of the scatter plot in Figure 1 that there is a linear relationship between the expected ease of intubation and the age of the patient, and also that the variance of the ease of intubation is constant with respect to the age of the patient. Finally, we will also assume that the conditional distribution of the ease of intubation given age is normal. Thus the requirements for fitting a linear regression model are met, so we will now fit the model.

```{R}
alpha = 0.05

model <- lm(ease ~ age, data=lar)
summary(model)
confint(model, 'age', level=0.95)
```

The estimated equation for the linear regression model is as follows:

$$
ease = 8.78 + 0.648 \times age
$$

The intercept coefficient of 8.78 indicates that the expected ease of intubation for a newborn baby (with age 0) would be 8.78. The age coefficient of 0.648 indicates that there is an increase in the ease of intubation score of 0.648 for each additional year in the age of the patient. We are 95% confident that the true change in ease of intubation for each additional year in age is between 0.194 and 1.101.

We would like to test whether the fit model describes a significant linear dependence between the ease of intubation and the age of the patient. The null hypothesis is that there is no change in the expected value of ease of intubation for a unit change in the age of the patient. The alternative hypothesis is that there is a non-zero change in the expected value of ease of intubation for a unit change in the age of the patient. We will test these hypotheses at a significance level of 0.05. 

The t statistic for the age coefficient in the linear model is 2.84. This implies that the slope is 2.84 standard errors from the null hypothesis value of 0. The p-value indicates that we would have a 0.56% chance of observing a slope this extreme if the null hypothesis were true. Using a significance level of 5%, we can reject the null hypothesis. We have moderate evidence that there is a weak but non-zero linear relationship between the ease of intubation and the age of the patient. The coefficient of determination states that 8.58% of the total variation in the ease of intubation is explained by the patient's age.

```{R}
age = 40
ease = 8.78 + 0.648 * age
ease
```
We can use the estimated linear model to predict the ease of intubation for a 40 year old patient by substituting the predictor value of 40 into the equation above. The age of the patient is within the range of the sample data that was used to fit the model, so this prediction is not considered extrapolation. In addition, we have verified with a hypothesis test that the data is explained by a significant linear relationship. Therefore, it is valid to use the linear model to make predictions for patients of age 40. The outcome value of 34.7 suggests that a 40 year old patient has an expected ease of intubation of 34.7.

In conclusion, we have discovered evidence of a significant but weak correlation between the ease of intubation procedures and the age of the patient. A newborn patient has an expected ease of intubation of 8.78, while each additional year in age increases their expected ease of intubation by 0.648. Furthermore, 8.58% of the total variation in ease of intubation is explained by the patient's age.
